  GenerateFinancialReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.generate_financial_report_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - S3WritePolicy:
            BucketName: !Ref WebsiteBucket
        - S3WritePolicy:
            BucketName: !Ref ReceiptsBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        GenerateReportApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /generate-financial-report
            Method: post

  ListReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.list_reports_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref WebsiteBucket
        - S3ReadPolicy:
            BucketName: !Ref ReceiptsBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        ListReportsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /list-reports
            Method: get
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GenAI-Enhanced Accounting Management System - Serverless MVP

Parameters:
  WebsiteBucketName:
    Type: String
    Default: genai-accounting-website
    Description: Name for the S3 bucket hosting the static website
  ReceiptsBucketName:
    Type: String
    Default: genai-accounting-receipts
    Description: Name for the S3 bucket storing receipt files
  RegionForBedrock:
    Type: String
    Default: ap-southeast-1
    AllowedValues:
      - ap-southeast-1
      - us-east-1
    Description: AWS region for Bedrock (model availability limited)
  ModelId:
    Type: String
    Default: amazon.nova-lite-v1:0
    AllowedValues:
      # Anthropic Claude models (available in ap-southeast-1)
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-3-5-sonnet-20240620-v1:0
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-5-sonnet-20241022-v2:0
      # Amazon Nova models (available in ap-southeast-1)
      - amazon.nova-pro-v1:0
      - amazon.nova-lite-v1:0
      - amazon.nova-micro-v1:0
      # Meta Llama models (if switching to us-east-1)
      - meta.llama3-2-1b-instruct-v1:0
      - meta.llama3-2-3b-instruct-v1:0
      - meta.llama3-2-11b-instruct-v1:0
      - meta.llama3-2-90b-instruct-v1:0
      - meta.llama3-1-8b-instruct-v1:0
      - meta.llama3-1-70b-instruct-v1:0
      # Mistral models
      - mistral.mistral-7b-instruct-v0:2
      - mistral.mixtral-8x7b-instruct-v0:1
      - mistral.mistral-large-2402-v1:0
      - mistral.mistral-large-2407-v1:0
      # Amazon Nova models
      - amazon.nova-micro-v1:0
      - amazon.nova-lite-v1:0
      - amazon.nova-pro-v1:0
      # Claude models (legacy support)
      - anthropic.claude-3-5-sonnet-20240620-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      # DeepSeek (custom integration)
      - deepseek-chat
      - deepseek-coder
    Description: AI model ID for receipt classification and insights generation
  # PostgreSQL Database Parameters
  OrganizationId:
    Type: String
    Description: Organization UUID for multi-tenant separation
  DatabaseHost:
    Type: String
    Description: PostgreSQL RDS endpoint hostname
  DatabasePort:
    Type: String
    Default: "5432"
    Description: PostgreSQL port
  DatabaseName:
    Type: String
    Default: accounting
    Description: PostgreSQL database name
  DatabaseUser:
    Type: String
    Description: PostgreSQL username
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: PostgreSQL password

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        # PostgreSQL Database Configuration
        ORG_ID: !Ref OrganizationId
        DB_HOST: !Ref DatabaseHost
        DB_PORT: !Ref DatabasePort
        DB_NAME: !Ref DatabaseName
        DB_USER: !Ref DatabaseUser
        DB_PASSWORD: !Ref DatabasePassword
        # AWS Services
        BUCKET_NAME: !Ref ReceiptsBucket
        MODEL_ID: !Ref ModelId
        BEDROCK_REGION: !Ref RegionForBedrock

Resources:
  # S3 Bucket for static website
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${WebsiteBucketName}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, POST, PUT, DELETE, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3000

  # Temporarily commented out due to policy issues
  # WebsiteBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref WebsiteBucket
  #     PolicyDocument:
  #       Statement:
  #         - Sid: PublicReadGetObject
  #           Effect: Allow
  #           Principal: "*"
  #           Action: s3:GetObject
  #           Resource: !Sub "${WebsiteBucket}/*"

  # S3 Bucket for receipts storage
  ReceiptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ReceiptsBucketName}-${AWS::AccountId}"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, POST, PUT, DELETE, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3000

  # Lambda Functions for PostgreSQL-based API
  ClassifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.classify_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ReceiptsBucket
        - S3WritePolicy:
            BucketName: !Ref ReceiptsBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        ClassifyApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /classify
            Method: post

  TransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.transactions_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        TransactionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /transactions
            Method: get

  SummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.summary_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        SummaryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /summary
            Method: get

  ReportMonthlyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.report_monthly_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        ReportMonthlyApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /report/monthly
            Method: get

  ForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.forecast_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        ForecastApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /forecast
            Method: get

  InsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.insights_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        InsightsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /insights
            Method: post

  # AI Chatbot Functions
  TaxAdvisorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.tax_advisor_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        TaxAdvisorApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /ai/tax-advisor
            Method: post

  FinancialAdvisorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.financial_advisor_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        FinancialAdvisorApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /ai/financial-advisor
            Method: post

  BudgetRecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.budget_recommendations_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        BudgetRecommendationsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /ai/budget-recommendations
            Method: post

  AiChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.ai_chat_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub "arn:aws:bedrock:${RegionForBedrock}::foundation-model/${ModelId}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        AiChatApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /ai/chat
            Method: post

  # Authentication Functions
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.login_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.register_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /register
            Method: post

  AuthCurrentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.auth_current_handler
      Layers:
        - !Ref PsycopgLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        AuthCurrentApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/current
            Method: get

  # Lambda Layer for psycopg2
  PsycopgLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: psycopg2-layer
      Description: PostgreSQL adapter for Python
      ContentUri: layers/psycopg2/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  WebsiteBucketName:
    Description: Name of the S3 bucket for website hosting
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteBucketName"

  WebsiteUrl:
    Description: URL for the static website
    Value: !Sub "http://${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteUrl"

  ReceiptsBucketName:
    Description: Name of the S3 bucket for receipts storage
    Value: !Ref ReceiptsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ReceiptsBucketName"

  DatabaseConfiguration:
    Description: PostgreSQL database configuration (host and database name)
    Value: !Sub "${DatabaseHost}:${DatabasePort}/${DatabaseName}"
    Export:
      Name: !Sub "${AWS::StackName}-DatabaseConfig"